### ISSUE TITLE
can only concatenate str (not "dict") to str

### ISSUE THREAD

**Issue by ferranferrer** [fyukcell/Google-Maps-Scraper#1]
First of all thanks for your development, when I run with same characters and my apiKey I found this issue:

"
Running turn: 0
Search Type: nearbysearch
Keyword: remodel
Traceback (most recent call last):
  File "gms.py", line 148, in <module>
    main()
  File "gms.py", line 46, in main
    businessFinder(searchType[z % 2], keyword[k])
  File "gms.py", line 79, in businessFinder
    print("PROBLEM DETECTED: " + result)
TypeError: can only concatenate str (not "dict") to str
"

**Comment by deadlinkdead** [comment]
Error found

You have to change line 79 --> print("PROBLEM DETECTED: " + result) to --> print("PROBLEM DETECTED: " , result).
You have to change the + into , 
In python pn can't add a dict via + so you have to display it after with the comma.
This should work now
